# Generated by Django 5.0 on 2023-12-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_bedroom',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_birthroom',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_kitchen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
